name: canary_checks

on:
  schedule:
    - cron: '0 12 * * *' # every day 12:00 UTC
  workflow_dispatch:

jobs:
  local_checks_with_latest_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - uses: ./.github/actions/setup_node
  #      - name: Install and build without lock file
  #        shell: bash
  #        run: |
  #          rm package-lock.json
  #          npm install
  #          npm run build
  #      - name: Check dependencies
  #        shell: bash
  #        run: |
  #          npm run check:dependencies
  #      - name: Run unit and integration tests
  #        shell: bash
  #        run: |
  #          npm run test
  log-failure-metric:
    runs-on: ubuntu-latest
    needs: [local_checks_with_latest_dependencies]
    permissions:
      # these permissions are required for the configure-aws-credentials action to get a JWT from GitHub
      id-token: write
      contents: read
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - name: Log failure
        uses: ./.github/actions/log-metric
        with:
          metric-name: WorkflowExecutionFailure
          value: 1
          dimensions: workflow=canary_checks,ref_name=${{ github.ref_name }}
          role-to-assume: ${{ secrets.METRICS_EMITTER_ROLE_ARN }}
          aws-region: us-west-2
  log-success-metric:
    runs-on: ubuntu-latest
    needs: [local_checks_with_latest_dependencies]
    permissions:
      # these permissions are required for the configure-aws-credentials action to get a JWT from GitHub
      id-token: write
      contents: read
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # version 3.6.0
      - name: Log success
        uses: ./.github/actions/log-metric
        with:
          metric-name: WorkflowExecutionFailure
          value: 0
          dimensions: workflow=canary_checks,ref_name=${{ github.ref_name }}
          role-to-assume: ${{ secrets.METRICS_EMITTER_ROLE_ARN }}
          aws-region: us-west-2
