# Description: This workflow mimic the flow of behaviors when user using Amplify CLI;

name: 'poc-e2e-flow-test'

on:
  push:
    branches:
      - poc/e2e-test

jobs:
  create-amplify-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [18]
        pkg-manager: [npm, yarn, yarn-stable, pnpm]
    runs-on: ${{ matrix.os }}
    env:
      PACKAGE_MANAGER_EXECUTABLE: ${{ matrix.pkg-manager }} # TODO: remove PACKAGE_MANAGER_EXECUTABLE once CLI is able to getPackageManager().
    steps:
      - name: Checkout aws-amplify/amplify-cli repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1. TODO: try only fetch .github/workflow
      - name: Setup Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 #4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Local Publish create-amplify
        shell: bash
        run: npm run install:local && npm run build && npm run vend
      - name: ${{matrix.pkg-manager}}-create-amplify-project
        if: matrix.pkg-manager != 'yarn-stable'
        shell: bash
        run: |
          mkdir -p /tmp/amplify-project; cd /tmp/amplify-project
          npm install -g ${{matrix.pkg-manager}}
          echo "$(${{matrix.pkg-manager}}) config set registry http://localhost:4873"
          ${{matrix.pkg-manager}} config set registry http://localhost:4873
          echo "$(${{matrix.pkg-manager}}) config get registry"
          ${{matrix.pkg-manager}} config get registry
          ${{matrix.pkg-manager}} create amplify --yes

      - name: yarn-stable-create-amplify-project
        if: matrix.pkg-manager == 'yarn-stable'
        shell: bash
        run: |
          mkdir -p /tmp/amplify-project; cd /tmp/amplify-project
          corepack enable
          echo "yarn set version stable"
          yarn set version stable
          echo "yarn version $(yarn --version)"
          yarn config set unsafeHttpWhitelist localhost
          yarn config set npmRegistryServer http://localhost:4873
          yarn create amplify --yes
