name: validate_cdk_release

on:
  schedule:
    # Every day at 16:00 UTC (8:00 PST) and 18:00 UTC (10:00 PST)
    # So that it produces at least 2 data points daily.
    - cron: '0 16,18 * * *'
  workflow_dispatch:
    inputs:
      desired-cdk-lib-version:
        description: 'AWS CDK Lib version (exact or tag). Defaults to latest version.'
        required: false
        type: string

jobs:
  health_checks_with_cdk_version:
    uses: ./.github/workflows/health_checks.yml
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      actions: read
      security-events: write
      id-token: write
    with:
      # This runs all deployment and sandbox tests.
      desired-cdk-lib-version: ${{ inputs.desired-cdk-lib-version || 'latest' }}
      # Exclude additional runtimes.
      # They don't bring much value, but may bring instability and extra latency.
      include-macos: false
      include-windows: false
      node: '["18"]'
      # Exclude package manager and create-amplify tests.
      # They don't bring functional coverage for CDK usage patterns.
      include-package-manager-e2e-tests: false
      include-create-amplify-e2e-tests: false
